DocCare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('department/',include('departments.urls')),
    path("",include("credentials.urls")),
    path("doctor/",include("doctors.urls")),
    path("patient/",include("patient.urls")),
    path("dashboard/",include("dashboards.urls")),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

credentials/urls.py
from django.urls import path
from credentials import views

app_name="credentials"

urlpatterns=[
    path("register",views.register,name="signup"),
    path("logout",views.logout,name="signout"),
    path("login",views.login,name="signin"),
    path("",views.home,name="home_page")
]

dashboards/urls.py
from django.urls import path
from dashboards import views


app_name="dashboards" 

urlpatterns=[
    path("manager-dashboard",views.managerDashboard,name="manager_dashboard")
]

departments/urls.py
from django.urls import path
from departments import views

app_name="departments"

urlpatterns=[
    path("add-department",views.addDepartment ,name="add_dep"),
    path("all-department",views.AllDepartments,name="list_dep")
]

doctors/urls.py
from django.urls import path
from doctors import views


app_name="doctors"
urlpatterns=[
    path("add-doctor",views.addDoctor,name="add_doctor"),
    path("list_doctor",views.viewDoctor,name="list_doctor"),
    path("edit-doctor/<int:dr_id>", views.editDoctor, name="edit_doctor")

]

dashboards/models.py
from django.db import models

# Create your models here.

dashboards/views.py
from django.shortcuts import render

# Create your views here.

def managerDashboard(request):
    return render(request,"dashboards/manager_dashboard.html")

templates/dashboards/manager_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <a href="{% url 'departments:add_dep'%}">Add Departments</a>
        <a href="{% url 'doctors:add_doctor'%}">Add Doctros</a>
        {% if request.user.is_authenticated %}
           <a href="{% url 'credentials:signout'%}">Logout</a>
        {% endif %}
    </nav>
    <div>
        <h1>Manager Dashboard</h1>
    </div>
</body>
</html>